<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="4.49.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="151.0.7922.13800" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ExamTicketGenerator\ExamTicketGenerator.csproj" />
  </ItemGroup>

</Project>
